import type { CSSProperties } from 'react'

// Dovena-inspired: warm cream page bg, burnt-orange accent, taupe muted text,
// generous section rhythm, pill buttons, softly rounded cards with hairline borders.
export const editableRootStyle = {
  '--slot4-page-bg': '#fbf7f2',
  '--slot4-page-text': '#1c140c',
  '--slot4-panel-bg': '#f5efe6',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#625a53',
  '--slot4-soft-muted-text': '#8b8078',
  '--slot4-accent': '#d97f50',
  '--slot4-accent-fill': '#d97f50',
  '--slot4-accent-soft': '#f6e5d8',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1c140c',
  '--slot4-dark-text': '#faf5ee',
  '--slot4-media-bg': '#efe8dd',
  '--slot4-cream': '#faf5ee',
  '--slot4-warm': '#f5efe6',
  '--slot4-lavender': '#efe4d4',
  '--slot4-gray': '#f0e9de',
  '--slot4-taupe': '#aa917a',
  '--slot4-taupe-deep': '#856e5a',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#fbf7f2',
  '--editable-page-text': '#1c140c',
  '--editable-container': '1368px',
  '--editable-border': 'rgba(110,110,110,0.20)',
  '--editable-border-strong': 'rgba(28,20,12,0.14)',
  '--editable-nav-bg': '#fbf7f2',
  '--editable-nav-text': '#1c140c',
  '--editable-nav-active': '#d97f50',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#d97f50',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#1c140c',
  '--editable-footer-text': '#faf5ee',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_2px_rgba(28,20,12,0.05)]',
  shadowStrong: 'shadow-[0_20px_60px_rgba(28,20,12,0.10)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(28,20,12,0.05),rgba(28,20,12,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-12',
    sectionY: 'py-20 sm:py-24 lg:py-32',
    sectionYLarge: 'py-24 sm:py-32 lg:py-40',
    sectionYSmall: 'py-12 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-8 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-16 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-6 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'text-[11px] font-medium uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-[3rem] font-medium leading-[1.02] tracking-[-0.035em] sm:text-[4.5rem] lg:text-[6rem]',
    sectionTitle: 'editable-display text-[2.25rem] font-medium leading-[1.08] tracking-[-0.03em] sm:text-[3rem] lg:text-[3.5rem]',
    subsectionTitle: 'editable-display text-2xl font-medium leading-[1.15] tracking-[-0.02em] sm:text-3xl',
    body: 'text-base leading-[1.7] text-[var(--slot4-muted-text)]',
    lead: 'text-lg leading-[1.6] text-[var(--slot4-muted-text)] sm:text-xl',
    emphasis: 'editable-display text-xl font-medium leading-[1.4] tracking-[-0.015em] text-[var(--slot4-page-text)] sm:text-2xl',
  },
  badge: {
    pill: 'inline-flex items-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-4 py-1.5 text-[11px] font-medium uppercase tracking-[0.22em] text-[var(--slot4-muted-text)]',
    accentPill: 'inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-4 py-1.5 text-[11px] font-medium uppercase tracking-[0.22em] text-[var(--slot4-accent)]',
  },
  surface: {
    card: `rounded-[28px] border ${editablePalette.border} ${editablePalette.surfaceBg}`,
    soft: `rounded-[28px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[28px] ${editablePalette.darkBg} ${editablePalette.darkText}`,
    raised: `rounded-[28px] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `editable-btn inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-medium tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-95 active:scale-[0.98]`,
    secondary: `editable-btn inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border-strong)] bg-transparent px-7 py-3.5 text-sm font-medium tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `editable-btn inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-medium text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-95 active:scale-[0.98]`,
    ghost: `inline-flex items-center gap-2 text-sm font-medium text-[var(--slot4-page-text)] transition duration-300 hover:text-[var(--slot4-accent)]`,
    dark: `editable-btn inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-dark-bg)] px-7 py-3.5 text-sm font-medium text-[var(--slot4-dark-text)] transition duration-300 hover:opacity-90 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[24px] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[32px] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
    ratioWide: 'aspect-[16/9]',
    ratioCinema: 'aspect-[21/9]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:shadow-[0_20px_60px_rgba(28,20,12,0.12)]',
    fade: 'transition duration-500 hover:opacity-85',
    zoom: 'transition duration-700 hover:scale-[1.02]',
  },
} as const

export const aiLayoutRules = [
  'All colors flow from editableRootStyle CSS variables — never hardcode.',
  'Section rhythm uses dc.shell.sectionY (large) or sectionYSmall (compact bands).',
  'Buttons use dc.button.primary/secondary — pill shape with sweep overlay.',
  'Cards use dc.surface.card with soft hairline borders and rounded-[28px] corners.',
  'Headings use editable-display class (Geist) with tight tracking.',
  'Wrap section headers + grid items in EditableReveal for staggered fade-up.',
  'Keep dynamic post fetching intact; do not replace posts with mocks.',
  'Use postHref() for all post links so task routes work.',
] as const
